# Scalar

In [16]:
import torch

x = torch.tensor(3)
y = torch.tensor(9)

w = torch.rand(1,requires_grad=True)
b = torch.rand(1,requires_grad=True)

z = torch.sigmoid(w*x+b)
y_pred = z
loss = torch.abs(y_pred-y)

In [17]:
print(w.grad,b.grad)
loss.backward()
print(w.grad,b.grad)

None None
tensor([-0.1086]) tensor([-0.0362])


# vector

In [35]:
x = torch.ones(3,requires_grad=True)
y = torch.relu((x**3).mean())

print(x.grad)
y.backward()
print(x.grad)

None
tensor([1., 1., 1.])


# clearing gradient

In [102]:
x = torch.tensor([2],requires_grad=True,dtype=torch.float16)

y = x**2

y.backward()
print(x.grad)
x.grad.zero_

tensor([4.], dtype=torch.float16)


<function Tensor.zero_>

In [94]:
print(x.grad)

tensor([4.], dtype=torch.float16)


# turn off gradient tracking reduces computation graph overhead

In [107]:
x = torch.tensor(1.2,requires_grad=True)
# x.requires_grad_(False)

# y = x.detach() # new tenson with not grad
# y

with torch.no_grad():
  y = x**2

y

tensor(1.4400)