In [1]:
import torch

if torch.cuda.is_available():
  print('hell yeah')
else:
  print('nah')

hell yeah


#create

In [2]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
torch.ones(1,1,2)

tensor([[[1., 1.]]])

In [4]:
torch.manual_seed(100)
temp = torch.rand(2,3)
print(temp)
print(type(temp))
print(temp.shape)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
<class 'torch.Tensor'>
torch.Size([2, 3])


# Data Type

In [5]:
x = torch.ones(2,3)
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# GPU tensors

In [6]:
import time

In [7]:
import time
import torch

n = 10000
x = torch.rand(n,n)
y = torch.rand(n,n)

start_cpu_time = time.time()
z = torch.matmul(x,y)
total_cpu_time = time.time()-start_cpu_time

device = torch.device('cuda')
a = x.to(device)
b = torch.rand(n,n,device=device)

start_gpu_time = time.time()
c = torch.matmul(a,b)
torch.cuda.synchronize()
total_gpu_time = time.time()-start_gpu_time

print(f"diff is {total_cpu_time-total_gpu_time}")
print(f"for cpu time is {total_cpu_time}")
print(f"for gpu time is {total_gpu_time}")

diff is 16.41365647315979
for cpu time is 17.065362453460693
for gpu time is 0.6517059803009033


# shape

In [8]:
x = torch.rand(3,4)
x.reshape(3,2,2)

tensor([[[0.0420, 0.8548],
         [0.3101, 0.2836]],

        [[0.2462, 0.5232],
         [0.4574, 0.1929]],

        [[0.9183, 0.1421],
         [0.0330, 0.8051]]])

In [9]:
x = torch.rand(2,3)
x.flatten()

tensor([0.0917, 0.0962, 0.9415, 0.8114, 0.6297, 0.3090])

In [10]:
x = torch.rand(226,226,3)
x.unsqueeze_(2)
x.shape

torch.Size([226, 226, 1, 3])

# numpy and pytorch

In [14]:
import numpy as np

x = torch.rand(3)
arr = x.numpy()
arr

tensor([0.2555, 0.7718, 0.1390])

In [21]:
arr = np.array([2,3,45,3])

x = torch.from_numpy(arr)
x

tensor([ 2,  3, 45,  3])