In [1]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;

In [ ]:
from sklearn.datasets import make_classification;
X,y=make_classification(n_samples=1000,n_features=9,n_classes=3,n_informative=6,random_state=50)


In [27]:
from sklearn.model_selection import train_test_split;
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.30,random_state=50)

In [93]:
X_train.shape
counts = pd.value_counts(y_train)
print(counts)

1    246
0    232
2    222
Name: count, dtype: int64


/tmp/ipykernel_6320/3127773372.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  counts = pd.value_counts(y_train)


In [80]:
from sklearn.linear_model import LogisticRegression;
logistic=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)

/home/cry-more/ml/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [81]:
y_pred_prob=logistic.predict_proba(X_test)

In [82]:
y_pred=logistic.predict(X_test);

In [83]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report;
score =accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
result=classification_report(y_test,y_pred)
print(result)

0.8333333333333334
[[90  4  7]
 [ 2 78  9]
 [ 9 19 82]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       101
           1       0.77      0.88      0.82        89
           2       0.84      0.75      0.79       110

    accuracy                           0.83       300
   macro avg       0.83      0.84      0.83       300
weighted avg       0.84      0.83      0.83       300



# hyperparameter tuning

In [84]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV

# Define the model
model = OneVsRestClassifier(LogisticRegression(max_iter=5000))

# Define parameter grid for the base LogisticRegression
params = [
    {"estimator__penalty": ["l2"], "estimator__solver": ["lbfgs", "newton-cg", "sag", "newton-cholesky"], "estimator__C": [1, 10, 0.1, 0.01]},
    {"estimator__penalty": ["l1"], "estimator__solver": ["liblinear", "saga"], "estimator__C": [1, 10, 0.1, 0.01]},
    {"estimator__penalty": ["elasticnet"], "estimator__solver": ["saga"], "estimator__C": [1, 10, 0.1, 0.01], "estimator__l1_ratio": [0.1, 0.5, 0.9]},
]

# Define cross-validation strategy
#cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Set up GridSearchCV
grid = GridSearchCV(
    estimator=model,
    param_grid=params,
    scoring="accuracy",
    cv=5,
    n_jobs=-1,
)

# Fit the grid search
grid.fit(X_train, y_train)

# Output best parameters and estimator
print("Best Parameters:", grid.best_params_)
print("Best Estimator:", grid.best_estimator_)


Best Parameters: {'estimator__C': 0.01, 'estimator__penalty': 'l2', 'estimator__solver': 'lbfgs'}
Best Estimator: OneVsRestClassifier(estimator=LogisticRegression(C=0.01, max_iter=5000))


In [86]:
y_pred=grid.predict(X_test)
score =accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
result=classification_report(y_test,y_pred)
print(result)

0.8133333333333334
[[88  6  7]
 [ 3 79  7]
 [10 23 77]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       101
           1       0.73      0.89      0.80        89
           2       0.85      0.70      0.77       110

    accuracy                           0.81       300
   macro avg       0.82      0.82      0.81       300
weighted avg       0.82      0.81      0.81       300

