In [7]:
import numpy as np;
lst=[1,2,3,4,5];
arr=np.array(lst);
print(arr);
print(arr.shape)

[1 2 3 4 5]
(5,)


In [23]:
arr2=np.array([11,29,31,42,90,65]);
arr2=arr2.reshape(2,3)
print(arr2.shape)
print(type(arr2))

(2, 3)
<class 'numpy.ndarray'>


In [24]:
print(np.sqrt(arr2))
print(np.sin(arr2))

[[3.31662479 5.38516481 5.56776436]
 [6.4807407  9.48683298 8.06225775]]
[[-0.99999021 -0.66363388 -0.40403765]
 [-0.91652155  0.89399666  0.82682868]]


In [26]:
a=np.array([[1,2,3]
,[4,5,6]
,[7,8,9]]);
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print(a[0][0])
print(a[0,1])

1
2


In [36]:
print(a[1:3][0:2])

[[4 5 6]
 [7 8 9]]


In [38]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Use slicing to get the desired subarray
print(a[1:3, 0:2])
print(a[1:3][0:2])

[[4 5]
 [7 8]]
[[4 5 6]
 [7 8 9]]


In [46]:
ary=np.array([1,2,3,4,5,6,7,8,9]);
print(ary[(ary>5) & (ary<5)])

[]
