In [49]:
from tensorflow.keras.models import load_model
import pickle
import tensorflow as tf
import pandas as pd

In [54]:
model=load_model("model.h5")

with open('one_hot_encoder.pkl',"rb") as f:
  ohe=pickle.load(f)

with open('standard_scalar.pkl',"rb") as f:
  ss=pickle.load(f)

with open('label_encoder.pkl',"rb") as f:
  lbl=pickle.load(f)

In [5]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
loss = tf.keras.losses.BinaryCrossentropy()
model.compile(optimizer=opt, loss=loss, metrics=["accuracy"])

In [55]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}
input_data["Gender"]=lbl.transform([input_data["Gender"]])[0]
df=pd.DataFrame([input_data])
arr=ohe.transform([[input_data["Geography"]]])
encoded_geo=pd.DataFrame(arr,columns=ohe.get_feature_names_out())
df=pd.concat([df,encoded_geo],axis=1)
df.drop(columns=["Geography"],inplace=True)
df

X=ss.transform(df)
X

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[-0.52524211,  0.91324755,  0.10269664, -0.69803417, -0.26338947,
         0.80485122,  0.64959174,  0.97238125, -0.85840673,  1.00125078,
        -0.58023704, -0.57542576]])

In [57]:
model.predict(X)   ##without compilong

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[0.02105379]], dtype=float32)

In [48]:
model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step


array([[0.02105379]], dtype=float32)